name: Install Python 
on: 
 push:
   branches:
      - main
jobs:
  check-python-version:
    runs-on: self-hosted
    steps:
     
      - name: whoami
        run: echo ${whoami}
      - name: systeminfo
        run: echo ${systeminfo}
